name: "Danger Go"
on: [pull_request]
jobs:
  danger:
    name: Danger Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Danger JS
        run: npm install -g danger

      - name: Install danger-go
        run: go install github.com/moolmanruan/danger-go/cmd/danger-go@v0.1.0 # match version used in build/ci

      - name: Check versions
        run: |
          go version
          danger-go -V
          danger -V

      - name: Run danger-go ci
        run: danger-go ci
        working-directory: ./build/ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Go tests
        run: go test -v ./...
